#!/usr/bin/env bash

# ANSI Color Codes
CYAN="\033[1;36m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
YELLOW="\033[1;33m"
GREEN="\033[1;32m"
ORANGE="\033[38;5;208m"
BOLD="\033[1m"
DIM="\033[2m"
RESET="\033[0m"

clear 2>/dev/null || true

echo -e "${BOLD}${CYAN}========================================================================================${RESET}"
echo -e "   ${BOLD}${PURPLE}🏛️  j-archive 시스템 아키텍처 터미널 플로우차트 (Terminal Flow Chart)${RESET}"
echo -e "${BOLD}${CYAN}========================================================================================${RESET}"
echo ""

echo -e " ${BOLD}${BLUE}[1. 사용자 요청 (Client Request)]${RESET}"
echo -e "   ${CYAN}┌────────────────────────────────────────────────────────────────────────┐${RESET}"
echo -e "   ${CYAN}│${RESET}  ${BOLD}🌐 방문자 웹 브라우저 (Chrome, Safari, 모바일)${RESET}                       ${CYAN}│${RESET}"
echo -e "   ${CYAN}│${RESET}     URL: ${GREEN}http://localhost:8000/blog/why-modern-php-is-awesome${RESET}            ${CYAN}│${RESET}"
echo -e "   ${CYAN}└───────────────────────────────────┬────────────────────────────────────┘${RESET}"
echo -e "                                       ${BOLD}│  1. HTTP GET Request${RESET}"
echo -e "                                       ${BOLD}▼${RESET}"
echo -e " ${BOLD}${BLUE}[2. 웹 서버 계층 (Web Server Layer)]${RESET}"
echo -e "   ${BLUE}┌───────────────────────────────────┴────────────────────────────────────┐${RESET}"
echo -e "   ${BLUE}│${RESET}  ${BOLD}⚡ 웹 서버 (Nginx / PHP Built-in CLI Server - Port 8000)${RESET}               ${BLUE}│${RESET}"
echo -e "   ${BLUE}│${RESET}     - 정적 파일 검사: ${DIM}이미지/CSS면 PHP 안 거치고 즉시 0.001초 응답${RESET}         ${BLUE}│${RESET}"
echo -e "   ${BLUE}│${RESET}     - 동적 웹 요청: ${PURPLE}public/index.php${RESET} 로 제어권 전달                       ${BLUE}│${RESET}"
echo -e "   ${BLUE}└───────────────────────────────────┬────────────────────────────────────┘${RESET}"
echo -e "                                       ${BOLD}│  2. FastCGI / Script Execute${RESET}"
echo -e "                                       ${BOLD}▼${RESET}"
echo -e " ${BOLD}${PURPLE}[3. 진입점 & 라우팅 (Core Routing)]${RESET}"
echo -e "   ${PURPLE}┌───────────────────────────────────┴────────────────────────────────────┐${RESET}"
echo -e "   ${PURPLE}│${RESET}  ${BOLD}🚪 Front Controller: ${CYAN}public/index.php${RESET}                                  ${PURPLE}│${RESET}"
echo -e "   ${PURPLE}│${RESET}     ${DIM}↓${RESET}"
echo -e "   ${PURPLE}│${RESET}  ${BOLD}🧭 Router Engine: ${CYAN}src/Router.php${RESET}                                         ${PURPLE}│${RESET}"
echo -e "   ${PURPLE}│${RESET}     URL 정규식 매칭: ${YELLOW}/blog/{slug}${RESET} ➔ ${GREEN}Controller Callback 매핑${RESET}            ${PURPLE}│${RESET}"
echo -e "   ${PURPLE}└───────────────────────────────────┬────────────────────────────────────┘${RESET}"
echo -e "                                       ${BOLD}│  3. 호출: getBlogPostWithNeighbors()${RESET}"
echo -e "                                       ${BOLD}▼${RESET}"
echo -e " ${BOLD}${YELLOW}[4. 데이터 & 마크다운 엔진 (Business Logic)]${RESET}"
echo -e "   ${YELLOW}┌───────────────────────────────────┴────────────────────────────────────┐${RESET}"
echo -e "   ${YELLOW}│${RESET}  ${BOLD}⚙️ Content Service: ${CYAN}src/ContentService.php${RESET}                                ${YELLOW}│${RESET}"
echo -e "   ${YELLOW}│${RESET}     - YAML Frontmatter 파싱 (제목, 카테고리, 태그, 날짜 추출)             ${YELLOW}│${RESET}"
echo -e "   ${YELLOW}│${RESET}     - ${ORANGE}Parsedown${RESET} 엔진 가동: ${GREEN}Markdown(.md) ➔ HTML 변환${RESET}                     ${YELLOW}│${RESET}"
echo -e "   ${YELLOW}│${RESET}     - 읽기 소요 시간(분) 자동 계산 & 이전글/다음글 네비게이션 연결        ${YELLOW}│${RESET}"
echo -e "   ${YELLOW}└───────────────┬────────────────────────────────────────┬───────────────┘${RESET}"
echo -e "                   ${BOLD}│ 4-A. JSON 읽기                         │ 4-B. Markdown 읽기${RESET}"
echo -e "                   ${BOLD}▼                                        ▼${RESET}"
echo -e "      ${GREEN}┌───────────────────────────┐            ┌────────────────────────────┐${RESET}"
echo -e "      ${GREEN}│${RESET} ${BOLD}📄 data/ 폴더 (정형 데이터)${RESET} ${GREEN}│${RESET}            ${GREEN}│${RESET} ${BOLD}📝 content/ 폴더 (문서 데이터)${RESET}${GREEN}│${RESET}"
echo -e "      ${GREEN}│${RESET}  - profile.json (개발자 J)  ${GREEN}│${RESET}            ${GREEN}│${RESET}  - blog/*.md (기술 블로그)  ${GREEN}│${RESET}"
echo -e "      ${GREEN}│${RESET}  - career.json  (경력)      ${GREEN}│${RESET}            ${GREEN}│${RESET}  - projects/*.md (프로젝트) ${GREEN}│${RESET}"
echo -e "      ${GREEN}│${RESET}  - side_projects.json       ${GREEN}│${RESET}            ${GREEN}└─────────────┬──────────────┘${RESET}"
echo -e "      ${GREEN}└─────────────┬─────────────┘                          │${RESET}"
echo -e "                    │                                        │${RESET}"
echo -e "                    └───────────────────┬────────────────────┘${RESET}"
echo -e "                                        ${BOLD}│  5. 파싱 완료된 데이터 객체 반환${RESET}"
echo -e "                                        ${BOLD}▼${RESET}"
echo -e " ${BOLD}${ORANGE}[5. 템플릿 합성 & 렌더링 (View Layer)]${RESET}"
echo -e "   ${ORANGE}┌────────────────────────────────────┴───────────────────────────────────┐${RESET}"
echo -e "   ${ORANGE}│${RESET}  ${BOLD}🎨 View Engine: ${CYAN}src/View.php${RESET}                                            ${ORANGE}│${RESET}"
echo -e "   ${ORANGE}│${RESET}     - XSS 보안 인코딩: ${GREEN}htmlspecialchars()${RESET}                                  ${ORANGE}│${RESET}"
echo -e "   ${ORANGE}│${RESET}     - 레이아웃 합성: ${CYAN}templates/layout.php${RESET}                                   ${ORANGE}│${RESET}"
echo -e "   ${ORANGE}│${RESET}       + 상단 네비게이션 & 3D 아바타 배지 & 다크모드 토글 스크립트          ${ORANGE}│${RESET}"
echo -e "   ${ORANGE}│${RESET}       + ${CYAN}templates/blog/show.php${RESET} (본문 + 코드복사 버튼 + 읽기진행바)         ${ORANGE}│${RESET}"
echo -e "   ${ORANGE}└────────────────────────────────────┬───────────────────────────────────┘${RESET}"
echo -e "                                        ${BOLD}│  6. 완성된 순수 HTML 스트림 출력${RESET}"
echo -e "                                        ${BOLD}▼${RESET}"
echo -e " ${BOLD}${GREEN}[6. 최종 화면 브라우저 렌더링 (Complete)]${RESET}"
echo -e "   ${GREEN}┌────────────────────────────────────┴───────────────────────────────────┐${RESET}"
echo -e "   ${GREEN}│${RESET}  ${BOLD}✨ 방문자 화면 렌더링 (평균 응답 속도: ${CYAN}2~4ms${RESET}${BOLD} - 초고속)${RESET}               ${GREEN}│${RESET}"
echo -e "   ${GREEN}│${RESET}     - Tailwind CSS 반응형 레이아웃 적용                                    ${GREEN}│${RESET}"
echo -e "   ${GREEN}│${RESET}     - Prism.js 문법 하이라이팅 적용                                        ${GREEN}│${RESET}"
echo -e "   ${GREEN}│${RESET}     - macOS 스타일 코드 복사 버튼 및 상단 스크롤 진행 바 작동              ${GREEN}│${RESET}"
echo -e "   ${GREEN}└────────────────────────────────────────────────────────────────────────┘${RESET}"
echo ""
echo -e "${BOLD}${CYAN}========================================================================================${RESET}"
echo -e " ${BOLD}💡 실행 명령어:${RESET} ${DIM}bash scripts/show-architecture.sh${RESET}"
echo -e "${BOLD}${CYAN}========================================================================================${RESET}"
